import type { PropostaKanban } from './types';

const comp = (itens: Array<[number, string, number, number]>) =>
  JSON.stringify(itens.map(([cargoId, nome, qty, custoMensal]) => ({ cargoId, nome, qty, custoMensal })));

/**
 * Fallback local (seed Vetta Facilities) usado quando a API não responde —
 * a página continua navegável e o gate server-side volta a mandar assim que a
 * conexão retorna.
 */
export const PROPOSTAS_EXEMPLO: PropostaKanban[] = [
  {
    id: 4,
    cliente: 'Rede de Farmácias BomPreço',
    contato: 'Ana Beatriz · (83) 98877-1122',
    escopo: '',
    sla: 'padrao',
    duracaoMeses: 12,
    composicao: comp([[2, 'Auxiliar de Limpeza', 0, 2600]]),
    custoTotal: 0,
    piso: 0,
    precoIA: 0,
    faixaTeto: 0,
    valorFinal: 0,
    descontoPct: 0,
    motivoDesvio: '',
    zona: 'verde',
    status: 'dados',
    vendedorId: 2,
    criadoEm: new Date('2026-08-14T10:00:00'),
    vendedorNome: 'Ana Beatriz',
    vendedorIniciais: 'AB',
  },
  {
    id: 3,
    cliente: 'Escola Futuro',
    contato: 'Direção · (83) 3222-8899',
    escopo: 'Limpeza e manutenção predial · 3 turnos',
    sla: 'padrao',
    duracaoMeses: 12,
    composicao: comp([
      [1, 'Técnico de Manutenção', 2, 4200],
      [2, 'Auxiliar de Limpeza', 6, 2600],
    ]),
    custoTotal: 24000,
    piso: 33333,
    precoIA: 33333,
    faixaTeto: 36666,
    valorFinal: 32300,
    descontoPct: 31,
    motivoDesvio: '',
    zona: 'verde',
    status: 'doc_selado',
    vendedorId: 1,
    criadoEm: new Date('2026-08-12T09:00:00'),
    vendedorNome: 'Nizan Jhon',
    vendedorIniciais: 'NJ',
  },
  {
    id: 2,
    cliente: 'Hospital Vida Nova',
    contato: 'Facilities · (83) 99911-4455',
    escopo: 'Limpeza crítica + supervisão dedicada',
    sla: 'padrao',
    duracaoMeses: 24,
    composicao: comp([
      [3, 'Aux. Limpeza Crítica', 4, 3400],
      [4, 'Supervisor de Conta', 1, 6800],
    ]),
    custoTotal: 20400,
    piso: 28333,
    precoIA: 28333,
    faixaTeto: 31166,
    valorFinal: 21800,
    descontoPct: 72,
    motivoDesvio: 'concorrência',
    zona: 'amarela',
    status: 'revisao_alcada',
    vendedorId: 1,
    criadoEm: new Date('2026-08-11T15:00:00'),
    vendedorNome: 'Nizan Jhon',
    vendedorIniciais: 'NJ',
  },
  {
    id: 1,
    cliente: 'Cond. Vista Park',
    contato: 'Síndica Márcia · (83) 99988-7766',
    escopo: 'Manutenção + limpeza das áreas comuns',
    sla: 'padrao',
    duracaoMeses: 12,
    composicao: comp([
      [1, 'Técnico de Manutenção', 2, 4200],
      [2, 'Auxiliar de Limpeza', 3, 2600],
    ]),
    custoTotal: 16200,
    piso: 22500,
    precoIA: 22500,
    faixaTeto: 24750,
    valorFinal: 13200,
    descontoPct: 139,
    motivoDesvio: 'relacionamento',
    zona: 'vermelha',
    status: 'aguardando_alcada',
    vendedorId: 1,
    criadoEm: new Date('2026-08-10T14:32:00'),
    vendedorNome: 'Nizan Jhon',
    vendedorIniciais: 'NJ',
  },
  {
    id: 5,
    cliente: 'Hotel Mar Azul',
    contato: 'Gerente de operações · (83) 99777-2211',
    escopo: 'Limpeza crítica da cozinha + manutenção',
    sla: 'padrao',
    duracaoMeses: 12,
    composicao: comp([
      [1, 'Técnico de Manutenção', 1, 4200],
      [3, 'Aux. Limpeza Crítica', 3, 3400],
    ]),
    custoTotal: 14400,
    piso: 20000,
    precoIA: 18900,
    faixaTeto: 20790,
    valorFinal: 18900,
    descontoPct: 0,
    motivoDesvio: '',
    zona: 'verde',
    status: 'elaborando',
    vendedorId: 1,
    criadoEm: new Date('2026-08-14T09:12:00'),
    vendedorNome: 'Nizan Jhon',
    vendedorIniciais: 'NJ',
  },
];
